### ISSUE TITLE
Unable to download Emmet. Please view the console for more details.

### ISSUE THREAD

**Issue by h46281793** [emmetio/sublime-text-plugin#164]
Unable to download Emmet. Please view the console for more details.
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
ignored packages updated to: ["Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading plugin Emmet.main
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\Lib\python38\sublime_plugin.py", line 312, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.8/importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 808, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\AppData\Roaming\Sublime Text\Packages\Emmet\main.py", line 18, in <module>
    from .lib import emmet_sublime, abbreviation, balance, syntax, comment, \
  File "C:\Users\Administrator\AppData\Roaming\Sublime Text\Packages\Emmet\lib\emmet_sublime.py", line 3, in <module>
    from ..emmet import expand as expand_abbreviation, extract, Config
ModuleNotFoundError: No module named 'Emmet.emmet'
reloading settings Packages/User/Preferences.sublime-settings

please help me!

**Comment by sergeche** [comment]
It’s an issue with your internet connection or Package Control. You should try to re-install plugin or create an issue in Package Control repo
