### ISSUE TITLE
no such prop background_color when matching auto_complete_details against auto_complete_details

### ISSUE THREAD

**Issue by fadrian06** [emmetio/sublime-text-plugin#186]
Hi, I code very much in PHP, I've seen too many errors with every character that I type within PHP code, the final error is this issue title...

- I use SublimeText 4-4169
- I use Emmet v2.4.1

And the console output is:
```
Traceback (most recent call last):
  File "C:\ProgramData\scoop\apps\sublime-text\4-4169\Lib\python38\sublime_plugin.py", line 959, in on_modified
    run_view_callbacks('on_modified', view_id)
  File "C:\ProgramData\scoop\apps\sublime-text\4-4169\Lib\python38\sublime_plugin.py", line 741, in run_view_callbacks
    callback(v, *args)
  File "C:\ProgramData\scoop\apps\sublime-text\4-4169\Lib\python38\sublime_plugin.py", line 162, in profiler
    return event_handler(*args)
  File "C:\ProgramData\scoop\persist\sublime-text\Data\Installed Packages\Emmet.sublime-package\main.py", line 45, in wrapper
    fn(self, view)
  File "C:\ProgramData\scoop\persist\sublime-text\Data\Installed Packages\Emmet.sublime-package\main.py", line 464, in on_modified
    abbreviation.handle_change(editor, get_caret(editor))
  File "C:\ProgramData\scoop\persist\sublime-text\Data\Installed Packages\Emmet.sublime-package\lib/abbreviation.py", line 353, in handle_change
    if editor_last_pos is not None and editor_last_pos == pos - 1 and allow_tracking(editor, pos):
  File "C:\ProgramData\scoop\persist\sublime-text\Data\Installed Packages\Emmet.sublime-package\lib/abbreviation.py", line 504, in allow_tracking
    if is_enabled(editor, pos) and syntax.in_activation_scope(editor, pos):
  File "C:\ProgramData\scoop\persist\sublime-text\Data\Installed Packages\Emmet.sublime-package\lib/abbreviation.py", line 524, in is_enabled
    return syntax_info['type'] == auto_mark
TypeError: 'NoneType' object is not subscriptable
no such prop background_color when matching auto_complete_details against auto_complete_details
```

**Comment by fadrian06** [comment]
The plugin works as normal, but that error in the Sublime console make hard debug other extensions
