### ISSUE TITLE
emmet_update_image_size is not working 

### ISSUE THREAD

**Issue by adragin** [emmetio/sublime-text-plugin#64]
Code:
```
<td>
	<img src="logo.png" width="" style="vertical-align:top;" alt="" />
</td>
```
keymap :
{ "keys": ["ctrl+u"], "caption": "Emmet: Update Image Size", "command": "emmet_update_image_size"}

And when I stay on image name and press ctrl+u nothing happens.

Traceback (most recent call last):
  File "C:\Sublime3\sublime_plugin.py", line 1088, in run_
    return self.run(edit)
  File "C:\Sublime3\Data\Installed Packages\Emmet.sublime-package\main.py", line 253, in run
  File "C:\Sublime3\Data\Installed Packages\Emmet.sublime-package\lib/update_image_size.py", line 17, in update_image_size
  File "C:\Sublime3\Data\Installed Packages\Emmet.sublime-package\lib/update_image_size.py", line 24, in update_image_size_html
AttributeError: 'module' object has no attribute 'tag'

**Comment by adragin** [comment]
while I was writing, a similar issue has already been created
